# Generated by Django 6.0.3 on 2026-04-20 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_review"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-date"],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"verbose_name": "Отзыв", "verbose_name_plural": "Отзывы"},
        ),
        migrations.RenameField(
            model_name="product",
            old_name="stock",
            new_name="count",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="created_at",
            new_name="date",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subcategories",
                to="catalog.category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="full_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="is_banner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_limited_edition",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="catalog.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="catalog.tag"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rate",
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
