# Generated by Django 6.0.3 on 2026-04-23 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="full_description",
            new_name="fullDescription",
        ),
        migrations.RemoveField(
            model_name="product",
            name="rating",
        ),
    ]
