# Generated by Django 6.0.3 on 2026-04-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_basket_basketitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
